### ISSUE TITLE
异常反馈：java.lang.NoSuchMethodError: No virtual method getLongVersionCode()

### ISSUE THREAD

**Issue by wenge1215** [ShowMeThe/WanAndroid#1]
无意中发现的问题，当手机连接网络，但是无法访问时报错
场景：1手机连接抓包工具进行抓包，2当网络不可访问时就会报错，3，页面会卡在加载页面
![bug](https://user-images.githubusercontent.com/21086803/67275714-c3c2d000-f4f5-11e9-965f-5ab8df37a558.PNG)

**Comment by ShowMeThe** [comment]
这个是我抓崩溃写入本队的代码，里面这个crash 有这个getLongVersionCode 如果没记错是version 28才加进去的，所以这个低版本手机的确会报这个，但不会导致程序崩溃，这个要到程序崩那刻他才工作的，所以崩溃是这个的前面发生的。 然后那个连接了不可访问的外网 我这边在NetworkWorkUtil下有一个请求ping的任务，所以应该是会读缓冲的数据，如果没有缓冲的确会停在加载页面但不是奔溃，你发现的奔溃估计是碰到那个放大图，我发布上传后我一段时间才发现代码被我误删，会导致崩溃。如果出现超时处理 ，在Result<T>这类和CallResult类有个对超时的监听，你可以看看 暂时这个项目我没用这块代码，后续会补上

**Comment by wenge1215** [comment]
感谢解答
